# Site Settings
title: Bitopma | Kho Phim Việt
email: moleys@protonmail.com
description: Chia sẻ phim Việt Nam.
baseurl: ""
url: "https://bitopma.gq"
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Bitopma
user_description: Thợ sửa ống nước.
disqus_username: bitopma

# Build settings
markdown: kramdown
highlighter: rouge
<<<<<<< HEAD
permalink: /:title/
=======
kramdown:
  input: GFM

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:title.html
<<<<<<< HEAD
>>>>>>> 4d0cf225cce8a7aa9b07320fbd0f993b248b9a2c
=======
>>>>>>> 4d0cf225cce8a7aa9b07320fbd0f993b248b9a2c

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Trang chủ
    url: /
  - title: Thông tin
    url: /about/
  - title: Liên hệ
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
